# permissions for end users to edit ovs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ovs-editor-role
rules:
- apiGroups:
  - ovs.openstack.org
  resources:
  - ovs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ovs.openstack.org
  resources:
  - ovs/status
  verbs:
  - get
