apiVersion: ovs.openstack.org/v1alpha1
kind: OVS
metadata:
  name: openvswitch
spec:
  replicas: 1
  containerImage: "quay.io/skaplons/ovs:latest"
  external-ids:
    system-id: "random"
    hostname: "devcontainer"
    ovn-bridge: "br-int"
    ovn-remote: "tcp:1.2.3.4:6442"
    ovn-encap-type: "geneve,vxlan"
    ovn-encap-ip: "10.20.30.40"

