apiVersion: ovs.openstack.org/v1beta1
kind: OVS
metadata:
  name: openvswitch
spec:
  ovsContainerImage: "quay.io/skaplons/ovs:latest"
  ovnContainerImage: "quay.io/tripleowallaby/openstack-ovn-controller:current-tripleo"
  external-ids:
    system-id: "random"
    ovn-bridge: "br-int"
    ovn-remote: "tcp:1.2.3.4:6442"
    ovn-encap-type: "geneve,vxlan"
    enable-chassis-as-gateway: false
  nic_mappings:
    physnet1: enp2s0.100
    physnet2: enp2s0.200
